// Downloads the self-hosted fonts (Google Fonts, SIL OFL) and regenerates
// src/styles/fonts.css. Run manually when refreshing typography:
//   node scripts/fetch-fonts.mjs
//
// Fonts are committed to the repository (public/fonts/) so the site never
// depends on Google at runtime and no visitor data reaches Google Fonts.

import fs from 'node:fs';
import path from 'node:path';

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const REQUESTS = [
  {
    family: 'Fraunces',
    cssUrl:
      'https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,300..700&display=swap',
    fileBase: 'fraunces',
  },
  {
    family: 'Nunito Sans',
    cssUrl:
      'https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,wght@0,200..1000;1,200..1000&display=swap',
    fileBase: 'nunito-sans',
  },
];

const OUT_DIR = path.join('public', 'fonts');
const CSS_OUT = path.join('src', 'styles', 'fonts.css');

function parseFontFaces(css) {
  const faces = [];
  const blocks = css.split('@font-face').slice(1);
  for (const block of blocks) {
    const body = block.slice(block.indexOf('{') + 1, block.indexOf('}'));
    const pick = (prop) => {
      const match = body.match(new RegExp(`${prop}\\s*:\\s*([^;]+);`));
      return match ? match[1].trim() : '';
    };
    const src = pick('src');
    const urlMatch = src.match(/url\(([^)]+)\)/);
    faces.push({
      style: pick('font-style') || 'normal',
      weight: pick('font-weight') || '400',
      unicodeRange: pick('unicode-range'),
      url: urlMatch ? urlMatch[1].replace(/['"]/g, '') : '',
    });
  }
  return faces;
}

const isLatin = (face) => face.unicodeRange.includes('U+0000-00FF');

const cssChunks = [
  '/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.',
  ' * Self-hosted Google Fonts (SIL Open Font License 1.1):',
  ' *   Fraunces — display serif (variable, weights 300–700)',
  ' *   Nunito Sans — body/interface sans (variable, weights 200–1000)',
  ' * License texts: docs/design/FONT-LICENSES.md',
  ' */',
  '',
];

fs.mkdirSync(OUT_DIR, { recursive: true });

for (const request of REQUESTS) {
  const response = await fetch(request.cssUrl, { headers: { 'User-Agent': UA } });
  if (!response.ok) {
    throw new Error(`Font CSS request failed for ${request.family}: HTTP ${response.status}`);
  }
  const css = await response.text();
  const latinFaces = parseFontFaces(css).filter(isLatin);
  if (latinFaces.length === 0) throw new Error(`No latin font faces found for ${request.family}`);

  for (const face of latinFaces) {
    const fileName = `${request.fileBase}-${face.style}-latin.woff2`;
    const fontResponse = await fetch(face.url, { headers: { 'User-Agent': UA } });
    if (!fontResponse.ok) throw new Error(`Font download failed: ${face.url}`);
    const buffer = Buffer.from(await fontResponse.arrayBuffer());
    fs.writeFileSync(path.join(OUT_DIR, fileName), buffer);
    cssChunks.push(
      '@font-face {',
      `  font-family: '${request.family}';`,
      `  font-style: ${face.style};`,
      `  font-weight: ${face.weight};`,
      '  font-display: swap;',
      `  src: url('/fonts/${fileName}') format('woff2');`,
      `  unicode-range: ${face.unicodeRange};`,
      '}',
      '',
    );
    console.log(`wrote public/fonts/${fileName} (${(buffer.length / 1024).toFixed(1)} KB)`);
  }
}

fs.writeFileSync(CSS_OUT, cssChunks.join('\n'));
console.log(`wrote ${CSS_OUT}`);
