"""Generate the committed strategic-analysis report from the canvassing data.

Output: docs/marketing/CANVASSING-ROUTES-OVERVIEW.md
Aggregate data only: no addresses, no coordinates, no owner information.

Usage: python scripts/canvass/build_report.py
"""

import csv
import json
import os

OUT = "canvass-out"
REPORT = os.path.join("docs", "marketing", "CANVASSING-ROUTES-OVERVIEW.md")


def read_csv(path):
    with open(path, newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def main():
    scores = json.load(open(os.path.join(OUT, "neighborhood_scores.json"), encoding="utf-8"))
    summary = json.load(open(os.path.join(OUT, "routes_summary.json"), encoding="utf-8"))
    routes = read_csv(os.path.join(OUT, "routes.csv"))
    addresses = read_csv(os.path.join(OUT, "master_addresses.csv"))

    # Top 25 streets by owner-occupied target homes within the selected routes.
    streets = {}
    for address in addresses:
        entry = streets.setdefault(address["Street_Name"], {"total": 0, "owner": 0, "neighborhood": address["Neighborhood"]})
        entry["total"] += 1
        if address["Owner_Occupied"] == "yes":
            entry["owner"] += 1
    top_streets = sorted(streets.items(), key=lambda item: (-item[1]["owner"], -item[1]["total"]))[:25]

    # Closest route clusters to the operating origin (driving estimate bands).
    clusters = {}
    for route in routes:
        driving = float(route["Estimated_Driving_Distance_Miles"] or 0)
        band = "0-5 mi" if driving <= 5 else "5-10 mi" if driving <= 10 else "10-15 mi" if driving <= 15 else "15-20 mi" if driving <= 20 else "20+ mi"
        entry = clusters.setdefault(band, {"routes": 0, "homes": 0, "neighborhoods": set()})
        entry["routes"] += 1
        entry["homes"] += int(route["Estimated_Home_Count"])
        entry["neighborhoods"].add(route["Neighborhood"])

    lines = [
        "# Canvassing routes — strategic overview",
        "",
        "Generated by `scripts/canvass/build_report.py` from the local canvassing database",
        "(public parcel records; address-level data stays in git-ignored `canvass-out/`).",
        "Routes come from the canonical engine (`scripts/canvass/route_engine.py`): contiguous",
        "balanced clusters, origin orientation, nearest-neighbour with same-street preference,",
        "deterministic 2-opt and efficiency-bounded street completion. Methodology:",
        "`docs/marketing/CANVASSING-SYSTEM.md`; engine contract and benchmark:",
        "`docs/marketing/field-acquisition/ROUTE-PLANNING.md`. Ranking:",
        "`docs/marketing/CANVASSING-TOP-NEIGHBORHOODS.md`.",
        "",
        "## Totals",
        "",
        f"- Neighborhoods targeted: **{summary['neighborhoods']}** (top-ranked subdivisions)",
        f"- Target homes mapped: **{summary['addresses']}** (owner-occupied: **{summary['owner_occupied']}**)",
        f"- Routes: **{summary['routes']}** — Priority A: {summary['priority_a_routes']}, Priority B: {summary['priority_b_routes']}, Priority C: {summary['priority_c_routes']}",
        f"- Estimated canvassing time: **~{summary['estimated_hours']} hours** (at ~30 homes/hour incl. travel between doors)",
        f"- Average route size: ~{round(summary['addresses'] / summary['routes'])} homes",
        "",
        "## Top 10 neighborhoods in the target set",
        "",
        "| Rank | Neighborhood | ZIP | SF homes | Score |",
        "| --- | --- | --- | --- | --- |",
    ]
    for row in scores[:10]:
        lines.append(f"| {row['rank']} | {row['neighborhood'].title()} | {row['zip_primary']} | {row['parcels']} | **{row['score']}** |")

    lines += [
        "",
        "## Top 25 streets by owner-occupied target homes",
        "",
        "| Rank | Street | Neighborhood | Target homes | Owner-occupied |",
        "| --- | --- | --- | --- | --- |",
    ]
    for index, (street, entry) in enumerate(top_streets, start=1):
        lines.append(f"| {index} | {street.title()} | {entry['neighborhood']} | {entry['total']} | {entry['owner']} |")

    lines += [
        "",
        "## Top routes (Priority A first, then size)",
        "",
        "| Route | Priority | Neighborhood | Homes | Walking mi | Drive mi (est.) | Score |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    ordered = sorted(routes, key=lambda route: (route["Priority"], -int(route["Estimated_Home_Count"])))
    for route in ordered[:50]:
        lines.append(
            f"| {route['Route_ID']} | {route['Priority']} | {route['Neighborhood']} | {route['Estimated_Home_Count']} | "
            f"{route['Estimated_Walking_Distance_Miles']} | {route['Estimated_Driving_Distance_Miles']} | {route['Neighborhood_Score']} |"
        )

    lines += [
        "",
        "## Closest route clusters to the operating origin (Cantonment area)",
        "",
        "| Drive band | Routes | Homes | Neighborhoods |",
        "| --- | --- | --- | --- |",
    ]
    for band in ["0-5 mi", "5-10 mi", "10-15 mi", "15-20 mi", "20+ mi"]:
        entry = clusters.get(band)
        if not entry:
            continue
        names = ", ".join(sorted(entry["neighborhoods"])[:6])
        lines.append(f"| {band} | {entry['routes']} | {entry['homes']} | {names} |")

    lines += [
        "",
        "## How to run a canvassing block",
        "",
        "1. Open `canvass-out/Canvassing-Workbook.xlsx` (Neighborhood Summary → Route Summary).",
        "2. Pick the next Priority A route; drive to its Start_Address.",
        "3. Print the matching page from `canvass-out/route_sheets.html` (one route per page).",
        "4. Knock every listed home; record Result / Notes / Follow-up on the sheet or in the",
        "   Performance Tracking tab (or `canvass-out/performance_tracking.csv`).",
        "5. After the block, update the tracking file; the recurring-customers-per-100-doors metric",
        "   is computed from the Booked / Recurring_Customer columns.",
        "",
        "Open `canvass-out/map.html` for the interactive map (route lines and priority colours).",
        "",
    ]
    with open(REPORT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print(f"wrote {REPORT}")


if __name__ == "__main__":
    main()
